behaviors:
  MarioAgent:
    trainer_type: ppo
    hyperparameters:
      batch_size: 32
      buffer_size: 2048
      learning_rate: 0.0003
      beta: 0.005
      epsilon: 0.1
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 128
      num_layers: 2
    reward_signals:
      extrinsic:
        gamma: 0.995
        strength: 0.75 # Increased reward strength to increase reinforcement learning
      gail:
        gamma: 0.85
        strength: .2 # Increased gail strength to increase curiosity
        demo_path: Assets/Demonstrations/MarioDemo.demo
    behavioral_cloning:
      gamma: 0.9
      strength: .25 # Decreased behavr_cloning strength
      demo_path: Assets/Demonstrations/MarioDemo.demo
    keep_checkpoints: 5
    max_steps: 750000
    time_horizon: 64
    summary_freq: 20000
    checkpoint_interval: 50000
    threaded: true