behaviors:
  MarioAgent:
    trainer_type: ppo
    hyperparameters:
      batch_size: 256
      buffer_size: 10240
      learning_rate: 0.0003
      beta: 0.0005
      epsilon: 0.2
      lambd: 0.99
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 512
      num_layers: 3
    reward_signals:
      extrinsic:
        gamma: 0.995
        strength: 0.1
      gail:
        strength: 0.5
        gamma: 0.995
        demo_path: Assets/Demonstrations/FirstLevelDemo.demo
    behavioral_cloning:
      strength: 1.0
      gamma: 0.995  
      demo_path: Assets/Demonstrations/FirstLevelDemo.demo
    keep_checkpoints: 5
    max_steps: 5000000
    time_horizon: 2048
    summary_freq: 20000
    threaded: true