# Reinforcement Learning for second level after training on imitation
behaviors:
  MarioAgent:
    trainer_type: ppo
    hyperparameters:
      batch_size: 256
      buffer_size: 1024
      learning_rate: 0.001
      beta: 0.0005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 5
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 512
      num_layers: 3
    reward_signals:
      extrinsic:
        gamma: 0.995
        strength: 0.8 # Increased impact of extrinsic reward to allow for reinforcement learning
      gail:
        strength: 0.2 # Decreased impact of GAIL in order to allow more room for reinforcement learning
        gamma: 0.995
        demo_path: Assets/Demonstrations/MarioDemo.demo
    behavioral_cloning:
      strength: 0.1 # Reduced impact of behavioral cloning
      gamma: 0.995
      demo_path: Assets/Demonstrations/MarioDemo.demo
    keep_checkpoints: 5
    max_steps: 5000000 # Increased max steps by 10x to account for the additional training
    time_horizon: 256
    summary_freq: 50000
    threaded: true